spring.application.name=clinic-backend
server.port=8080

# --- PostgreSQL ---
spring.datasource.url=jdbc:postgresql://localhost:5432/clinic_db
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=postgresqlpassword

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JWT config
app.jwt.secret=Cl1n1cM4n4g3m3ntS3cr3tK3yF0rJWTSign1ngMustBe256B1tsL0ng!
app.jwt.expiration-ms=86400000
